module.exports = {
    NAME: '',
    PORT: '',
    AUTH_SECRET: '',
    AUTH_BASE_URL: '',
    DB_NAME: '',
    DB_USER: '',
    DB_PASS: '',
    DB_HOST: '',
    DB_DIALECT: '',
    MAIL_HOST: '',
    MAIL_USER: '',
    MAIL_PASS: '',
    MAIL_PORT: '',
    BLOCKCYPHER_TOKEN: '',
    BLOCKCYPHER_API_URL: '',
    WALLET_PRIVATE_KEY: '',
    WALLET_PUBLIC_KEY: '',
    WALLET_WIF: '',
    WALLET_ADDRESS: '',
    TOTAL_FREE_SATOSHI: 0
}
